# Generated by Django 6.0.5 on 2026-05-25 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(unique=True, verbose_name='别名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('url', models.URLField(verbose_name='网站地址')),
                ('description', models.TextField(blank=True, verbose_name='网站描述')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='Logo地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('gitee', 'Gitee'), ('zhihu', '知乎'), ('weibo', '微博'), ('bilibili', 'B站'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('wechat', '微信公众号'), ('other', '其他')], default='github', max_length=20, verbose_name='平台')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='显示名称')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome或Element Plus图标类名', max_length=50, verbose_name='图标类名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '个人链接',
                'verbose_name_plural': '个人链接',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='我的个人博客', max_length=100, verbose_name='网站名称')),
                ('site_description', models.TextField(blank=True, verbose_name='网站描述')),
                ('site_keywords', models.CharField(blank=True, max_length=500, verbose_name='网站关键词')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub地址')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('about_content', models.TextField(blank=True, verbose_name='关于页面内容')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='别名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='别名')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='正文')),
                ('content_html', models.TextField(blank=True, editable=False, verbose_name='正文HTML')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='封面图片URL')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '已发布')], default='p', max_length=1, verbose_name='状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-is_top', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='昵称')),
                ('author_email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('author_url', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否审核通过')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='文章')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='父评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
    ]
